### ISSUE TITLE
Can't install via nuget

### ISSUE THREAD

**Issue by r3ndszergazda** [Wagnerp/Krypton-NET-4.7#32]
Could not install package 'KryptonToolkitSuite471 4.71.554'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Although the Project I'm trying to install it to is also .NET 4.7.1

**Comment by Wagnerp** [comment]
Hi @r3ndszergazda,

Thanks for your message. I've deliberately stopped uploading Nuget packages, due to this error. I did try to reach out to the Nuget team to see how I can resolve the issue. Unfortunately, I received no response. In the end, I chose to upload the binaries to the releases tab of this repo. Sorry for the inconvenience. Hopefully the Nuget packages will return... one day!

**Comment by r3ndszergazda** [comment]
Wow, thank you very much for your prompt and detailed response & also for your kindness! Thank you for the clarfication also!

**Comment by Wagnerp** [comment]
You're welcome.
